
---
title: foo
output:
   html_document:
     toc: trie
---


---
quarto:
  @quarto/tufte_handout:
    pandoc:
      variables:
        documentclass: book
        classoption:
          - twosides
          - draft
  computations:
      - foo.R
      - bar.xslx
      - spaz.ipynb
  extensions:
    - https://quarto.org/extensions/downlit  
    - https://quarto.org/extensions/fancy_tweet    
---

_quarto.yml

book:
        

output:
  tufte_handout:
    toc: true

pandoc:
  variables:
    documentclass: book
    classoption:
      - twosides
      - draft

extensions:
  - https://quarto.org/extensions/website@1.3.4  
  - https://quarto.org/extensions/tufte_handout 
  - https://quarto.org/extensions/downlit  
  - https://quarto.org/extensions/fancy_tweet 

latex:
  texlive packages








