 name: Archive Deno

 on:
  workflow_dispatch:
  push:
    paths:
    - package/versions.txt

 jobs:
   archive-deno:

     env:
      AWS_S3_BUCKET: ${{ secrets.AWS_ARCHIVE_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY }}      

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Setup Environment
       run: |
            source package/versions.txt
            echo "VERSION=$DENO" >> $GITHUB_ENV
            echo "BASEURL=https://github.com/denoland/deno/releases/download/" >> $GITHUB_ENV
            echo "FILENAMES=deno-x86_64-unknown-linux-gnu.zip deno-x86_64-apple-darwin.zip deno-x86_64-pc-windows-msvc.zip" >> $GITHUB_ENV

     - uses: ./.github/workflows/actions/archive
       with:
         binary-name: 'deno'
         version: ${{ env.VERSION }}
         base-url: ${{ env.BASEURL }}
         files: ${{ env.FILENAMES }}
         bucket: ${{ env.AWS_S3_BUCKET }}
