 name: Archive Pandoc-Crossref

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - package/versions.txt

 jobs:
   archive-pandoc-crossref:

     env:
      AWS_S3_BUCKET: ${{ secrets.AWS_ARCHIVE_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY }}      

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Setup Environment
       run: |
            source package/configure
            echo "VERSION=$PANDOCCROSSREF" >> $GITHUB_ENV
            echo "BASEURL= https://github.com/lierdakil/pandoc-crossref/releases/download/" >> $GITHUB_ENV
            echo "FILENAMES=pandoc-crossref-macOS.tar.xz pandoc-crossref-Linux.tar.xz pandoc-crossref-Windows.7z" >> $GITHUB_ENV

     - uses: ./.github/workflows/actions/archive
       with:
         binary-name: 'pandoc-crossref'
         version: ${{ env.VERSION }}
         base-url: ${{ env.BASEURL }}
         files: ${{ env.FILENAMES }}
         bucket: ${{ env.AWS_S3_BUCKET }}
