
 name: Archive Pandoc

 on:
  workflow_dispatch:
  push:
    paths:
    - package/versions.txt

 jobs:
   archive-pandoc:

     env:
      AWS_S3_BUCKET: ${{ secrets.AWS_ARCHIVE_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY }}      

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Setup Environment
       run: |
            source package/versions.txt
            echo "VERSION=$PANDOC" >> $GITHUB_ENV           
            echo "BASEURL=https://github.com/jgm/pandoc/releases/download/" >> $GITHUB_ENV
            echo "FILENAMES=pandoc-$PANDOC-linux-amd64.tar.gz pandoc-$PANDOC-macOS.zip pandoc-$PANDOC-windows-x86_64.zip" >> $GITHUB_ENV

     - uses: ./.github/workflows/actions/archive
       with:
         binary-name: 'pandoc'
         version: ${{ env.VERSION }}
         base-url: ${{ env.BASEURL }}
         files: ${{ env.FILENAMES }}
         bucket: ${{ env.AWS_S3_BUCKET }}

