


  
 name: Archive TinyTex

 on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - package/versions.txt

 jobs:
   archive-tinytex:

     env:
      AWS_S3_BUCKET: ${{ secrets.AWS_ARCHIVE_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ARCHIVE_ACCESS_KEY }}      

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2

     - name: Setup Environment
       run: |
            source package/configure
            echo "VERSION=$TINYTEX" >> $GITHUB_ENV
            echo "BASEURL=https://github.com/yihui/tinytex-releases/releases/download/" >> $GITHUB_ENV
            echo "FILENAMES=TinyTeX-1-$TINYTEX.tar.gz TinyTeX-1-$TINYTEX.tgz TinyTeX-1-$TINYTEX.zip" >> $GITHUB_ENV

     - uses: ./.github/workflows/actions/archive
       with:
         binary-name: 'tinytex'
         version: ${{ env.VERSION }}
         base-url: ${{ env.BASEURL }}
         files: ${{ env.FILENAMES }}
         bucket: ${{ env.AWS_S3_BUCKET }}
